---
title: "03_20_xenium_human_lung_cancer_report"
author: "Benedetta Banzi"
date: "2024-03-20"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
<STYLE TYPE="text/css">
<!--
  td{
    font-family: Arial; 
    font-size: 10 pt;
    padding:0px;
    cellpadding="0";
    cellspacing="0"
  }
  th {
    font-family: Arial; 
    font-size: 10 pt;
    height: 20px;
    font-weight: bold;
    text-align: "center";
    background-color: #ccccff;
    padding-left: 15px;
    padding-right: 15px;
  }
  table { 
    border-spacing: 4px;
    border-collapse: collapse;
  }
--->
</STYLE>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminary steps

Library import

```{r}
library(SpatialExperiment)
library(data.table)
library(scater) # it imports scuttle
library(cowplot)
library(ggplot2)
theme_set(theme_bw())
library(matrixStats)
library(dplyr)
library(tidyr)
library(tibble)
library(arrow)
library(scales)
library(sf)
library(tmap)
library(knitr)
library(grid)
library(ggpointdensity)
library(ggpubr)
library(spdep)
library(ggExtra)
library(DT)
library(e1071)
library(robustbase)
```

Read-in function

```{r}
readXeniumSPE <- function(dirname, 
                          countfname = "cell_feature_matrix.h5",
                          coordfpattern = "cells.csv.gz", 
                          coord_names = c("x_centroid", "y_centroid")){
  countfpath <- file.path(dirname, countfname)
  coord_file <- file.path(dirname, list.files(dirname, coordfpattern))
  
  # Count matrix + rowData
  sce <- DropletUtils::read10xCounts(countfpath, col.names = TRUE)
  
  # Spatial and colData
  colData <- read.csv(gzfile(coord_file), header = TRUE)
  
  # construct 'SpatialExperiment'
  spe <- SpatialExperiment::SpatialExperiment(
    assays = assays(sce),
    rowData = rowData(sce),
    colData = colData,
    spatialCoordsNames = coord_names
  )
  
  return(spe)
}
```

Setting directories

```{r}
dirname <- "/NAS06/work/Spatial_omics/Xenium/Human_lung_cancer"
sample_name <- "Xenium_human_lung_cancer"
```

# Xenium dataset exploratory analysis for preprocessing {.tabset .tabset-fade .tabset-pills}

SpatialExperiment object creation and exploration

```{r}
spe <- readXeniumSPE(dirname = dirname)
spe <- scuttle::addPerCellQC(spe, subsets=list(NegProb = grep("^NegControlProbe_", rownames(spe)), NegCodw = grep("^NegControlCodeword_", rownames(spe)), UnasCodw = grep("^UnassignedCodeword_", rownames(spe))))
names(colData(spe)@listData)
spe$control_counts <- rowSums(data.frame(colData(spe))[,grep("^subsets_.*_sum$", names(colData(spe)))])
spe$control_detected <- rowSums(data.frame(colData(spe))[,grep("^subsets_.*_detected$", names(colData(spe)))])
```
Dataset dimensions

```{r}
dim(spe)
```

Adding variables

```{r}
cell_boundaries <- read_parquet(file.path(dirname, "cell_boundaries.parquet"))
bound_sf <- st_as_sf(cell_boundaries, coords = c("vertex_x", "vertex_y"))

polygons <- bound_sf %>%
  group_by(cell_id) %>%
  summarize(geometry = st_combine(geometry))#st_combine = combine several feature geometries into one, without unioning or resolving internal boundaries

polygons <- st_cast(polygons, "POLYGON")

AspectRatio <- c()
for(i in 1:dim(polygons)[1]){
 AspectRatio[i] <- (max(polygons$geometry[[i]][[1]][,2]) - min(polygons$geometry[[i]][[1]][,2]))/(max(polygons$geometry[[i]][[1]][,1]) -
 min(polygons$geometry[[i]][[1]][,1]))
}
```

Added variables

```{r}
# Importing global coordinates from spatialCoords slot since they are not available in colData
colData(spe)$CenterX_global_um <- spatialCoords(spe)[,1]
colData(spe)$CenterY_global_um <- spatialCoords(spe)[,2]

# Logged total counts
spe$logtot <- log10(spe$total)

# Logged width/height ratio so there are no holes in the distribution in the middle and also negative values can be appreciated
spe$AspectRatio <- AspectRatio
spe$log2_AspectRatio <- log2(spe$AspectRatio)

# Keeping only target counts by subtracting counts referred to negative control probes
spe$target_counts <- spe$total - spe$control_counts

# Keeping only detected features by subtracting negative control probes
spe$target_detected <- spe$detected - spe$control_detected

# Proportion between counts referred only to target probes and detected features
spe$tot_det_ratio <- spe$target_counts/spe$target_detected

spe$ctrl_total_ratio <- spe$control_counts/spe$total
```

Custom polygons

```{r}
  terra_rast <- terra::rast(file.path(dirname, "morphology.ome.tif"))
  terra_polygon <- terra::as.polygons(terra_rast, value = TRUE)
  terra_polygon <- terra::fillHoles(terra_polygon)
  names(terra_polygon) <- c("cellID")
  terra_polygon$fov <- rep(which(tif_list == x), dim(terra_polygon)[1])
  valid_index <- terra::is.valid(terra_polygon)
  terra_polygon <- terra_polygon[valid_index]
  terra_polygon <- terra::flip(terra_polygon, direction = "vertical")
        shift_horizontal_step <- 0
        shift_vertical_step <- dim(terra_rast)[1]
        terra_polygon = terra::shift(terra_polygon,
                                     dx = shift_horizontal_step,
                                     dy = shift_vertical_step)
  if (terra_polygon$cellID[1]==0){
    terra_polygon <- terra::subset(terra_polygon, terra_polygon$cellID!=0)}
  st_as_sf(terra_polygon)      

```

```{r}

```







