---
title: "xenium_pancreas"
author: "Dario Righelli"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Reading Function

```{r}
library(SpatialExperiment)
readXeniumSPE <- function(dirname,
                          countfname = "cell_feature_matrix.h5",
                          coordfpattern = "cells.csv.gz",
                          coord_names = c("x_centroid", "y_centroid"))
{
    countfpath <- file.path(dirname, countfname)
    coord_file <- file.path(dirname, list.files(dirname, coordfpattern))

    # Count matrix + rowData
    sce <- DropletUtils::read10xCounts(countfpath, col.names = TRUE)

    # Spatial and colData
    colData <- read.csv(gzfile(coord_file), header = TRUE)

    # construct 'SpatialExperiment'
    spe <- SpatialExperiment::SpatialExperiment(
        assays = assays(sce),
        rowData = rowData(sce),
        colData = colData,
        spatialCoordsNames = coord_names
    )

    return(spe)
}
```


```{r}
spe <- readXeniumSPE("/Users/inzirio/Downloads/Xenium_data/pancreas/outs")
```


```{r}
library(scuttle)
spe <- addPerCellQC(spe)
colData(spe)
```


